version: '3.7'

services:
  nginx-lua:
    image: fabiocicerchia/nginx-lua:${NGINX_LUA_TAG}
    restart: always
    ports:
      - "${PORT}:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/handler.lua:/etc/nginx/handler.lua:ro
      - ./episodes:/var/episodes:ro
      - ./static:/usr/share/nginx/html/:ro
    healthcheck:
      test: ['CMD', 'curl --fail http://localhost/ || exit 1']
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - internal
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./episodes:/var/episodes:ro
      - ./static:/usr/share/nginx/html/:ro

networks:
  internal:
    driver: bridge