version: '3.7'

services:
  nginx-lua:
    image: fabiocicerchia/nginx-lua:1.23-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.tls.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/configs:ro
      - ./static:/usr/share/nginx/html/:ro
      - ./nginx-selfsigned.crt:/etc/ssl/certs/server.crt:ro
      - ./nginx-selfsigned.key:/etc/ssl/private/server.key:ro
    healthcheck:
      test: ['CMD', 'curl --fail http://localhost/ || exit 1']
      interval: 30s
      timeout: 3s
      retries: 3