---
- hosts: aws
  become: true
  user: ubuntu
  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/kavfixnel/nginx-random-episode.git
        dest: /home/ubuntu/nginx-random-episode
        clone: yes
        update: yes

    # Shut down server in case it's already running
    - name: Stop nginx-random-redirect
      ansible.builtin.shell:
        cmd: docker compose down
        chdir: /home/ubuntu/nginx-random-episode
      ignore_errors: true

    - name: Start nginx-random-redirect
      ansible.builtin.shell:
        cmd: docker compose up -d
        chdir: /home/ubuntu/nginx-random-episode
