---
- hosts: aws
  become: true
  user: ubuntu
  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/kavfixnel/nginx-random-episode.git
        dest: /home/ubuntu/nginx-random-episode
        clone: yes
        update: yes

    # Make sure the caddy_data docker volume exists
    - name: Create caddy_data docker volume
      ansible.builtin.shell:
        cmd: docker volume create caddy_data

    - name: Decrypt the configs/prometheus-remote-write.yaml file and attach configuration to configs/prometheus.yaml
      ansible.builtin.shell:
        cmd: 'sops -d --age $(cat $SOPS_AGE_KEY_FILE | grep -oP "public key: \(.*\)") configs/prometheus-remote-write.yaml >> configs/prometheus.yaml'
      environment:
        SOPS_AGE_KEY_FILE: ~/.sops/ci-key.txt

    # Shut down server in case it's already running
    - name: Stop nginx-random-redirect
      ansible.builtin.shell:
        cmd: docker compose down
        chdir: /home/ubuntu/nginx-random-episode
      ignore_errors: true

    - name: Start nginx-random-redirect
      ansible.builtin.shell:
        cmd: docker compose -f docker-compose.prod.yaml up -d
        chdir: /home/ubuntu/nginx-random-episode
